name: build-aya-bpf

on:
  push:
    branches:
      - main
      - ci

  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        arch:
          - x86_64
          - aarch64
          - arm
          # Disable riscv64 due to missing pt_regs handling in aya-bpf/args.rs
          # - riscv64
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-01-10
          components: rust-src
          override: true

      - uses: Swatinem/rust-cache@v1

      - name: Prereqs
        run: cargo install bpf-linker

      - name: Build
        env:
          CARGO_CFG_BPF_TARGET_ARCH: ${{ matrix.arch }}
        run: |
          cargo build-bpfel -p aya-bpf --verbose
          cargo build-bpfeb -p aya-bpf --verbose
          cargo build-bpfel -p aya-log-ebpf --verbose
          cargo build-bpfeb -p aya-log-ebpf --verbose
